### ISSUE TITLE
Search through URL

### ISSUE THREAD

**Issue by nakomaru** [ufx/GarlandTools#12]
Allow searching through URL links to support easy searching with modern browsers.

Something like: http://www.garlandtools.org/db/search?q=%s

**Comment by ufx** [comment]
This has actually been in place for a little while.  http://www.garlandtools.org/db/#search/fieldcraft, for example, will perform that search.  I've also just implemented tab searching on the domain if you use Chrome.  Try typing garlandtools.org<tab>your search.

**Comment by nakomaru** [comment]
Oh, great!

I've set up my own shorthand in chrome to search with http://www.garlandtools.org/db/#search/%s. This way I just type "gt[space][search]".

However, spaces are replaced with %20, which ruins the results. Can this be fixed?

**Comment by ufx** [comment]
Oops, it does!  I'll make this replace %20 with a space in tomorrow's update.
