### ISSUE TITLE
Rarefied spawn timers/missing nodes

### ISSUE THREAD

**Issue by xandris** [ufx/GarlandTools#21]
![image](https://user-images.githubusercontent.com/1970616/101598439-03c06d00-39ad-11eb-91ed-004e55e7be01.png)

I noticed [this TSV data](https://github.com/ufx/GarlandTools/blob/9fe87375a5939463cbe009e92f9f2746eff1da45/Supplemental/FFXIV%20Data%20-%20Nodes.tsv) just changed:

```
...
Rarefied Abalathian Spring Water		308	10, 22	120	20.6, 11.5	Unspoiled
Rarefied Aurum Regis Sand		308	10, 22	120	20.6, 11.5	Unspoiled
```

They say `10, 22`, but I would expect `2, 14`. I'd be happy to submit a PR for the nodes I have in my gathering log, but I don't know if these files are generated or what.

There are also some rarefied items that are missing like these ones:

![image](https://user-images.githubusercontent.com/1970616/101600335-053f6480-39b0-11eb-8b76-10638174a267.png)

I'm only in HW so not really impacted by most of those :)

**Comment by Supamiu** [comment]
It seems like the data export didn't go well for some of the new nodes, I'm on it in order to fix asap.

**Comment by Supamiu** [comment]
The data is crowd sourced from https://docs.google.com/spreadsheets/d/1hEj9KCDv0TT1NiGJ0S7afS4hfGMPb6tetqXQetYETUE/edit#gid=1571190523 btw 😄

**Comment by xandris** [comment]
Wonderful! Thank you!
