### ISSUE TITLE
Unable to use Garland Data

### ISSUE THREAD

**Issue by PineappleSkitter** [ufx/GarlandTools#35]
**Garland Data no longer seems to be working for me, and told me to post to the issue tracker. I've tried clearing my settings via the /error.html page but that doesn't seem to do anything.**

Oops! Something went wrong. Please copy the below message into a comment at the forums, or submit to our issue tracker. Go here to clear your settings: http://www.garlandtools.org/error.html.

gt.item.initialize@http://www.garlandtools.org/db/js/gt.item.js:14:3
gt.core.initialize@http://www.garlandtools.org/db/js/gt.core.js:19:4
n.Callbacks/j@https://code.jquery.com/jquery-2.1.1.min.js:2:26855
n.Callbacks/k.fireWith@https://code.jquery.com/jquery-2.1.1.min.js:2:27673
.ready@https://code.jquery.com/jquery-2.1.1.min.js:2:29465
I@https://code.jquery.com/jquery-2.1.1.min.js:2:29656

**Comment by PineappleSkitter** [comment]
It now seems to be working again.

**Comment by ufx** [comment]
Thanks for the report, I appreciate these every time.  It looks like this was caused by a network outage.  Part of the site loaded, and part didn't.  Usually these go away very quickly on their own.
