### ISSUE TITLE
Doing what the site told me to do

### ISSUE THREAD

**Issue by MesTheGod** [ufx/GarlandTools#36]
gt.time.initialize@http://www.garlandtools.org/db/js/gt.time.js:16:3
gt.core.initialize@http://www.garlandtools.org/db/js/fastclick.min.js:24:4
n.Callbacks/j@https://code.jquery.com/jquery-2.1.4.min.js:2:26920
n.Callbacks/k.fireWith@https://code.jquery.com/jquery-2.1.4.min.js:2:27738
.ready@https://code.jquery.com/jquery-2.1.4.min.js:2:29530
I@https://code.jquery.com/jquery-2.1.4.min.js:2:29721

**Comment by ufx** [comment]
Hi Mes, it looks like you ran into a network problem loading a file on the site.  This usually corrects itself if you wait a little while and refresh the page.  Sorry for the error!  Let me know if the problem persists.

**Comment by MesTheGod** [comment]
3 days alter and I'm still getting the same issue o_o

gt.time.initialize@http://www.garlandtools.org/db/js/gt.time.js:16:3
gt.core.initialize@http://www.garlandtools.org/db/js/gt.core.js:24:4
n.Callbacks/j@https://code.jquery.com/jquery-2.1.4.min.js:2:26920
n.Callbacks/k.fireWith@https://code.jquery.com/jquery-2.1.4.min.js:2:27738
.ready@https://code.jquery.com/jquery-2.1.4.min.js:2:29530
I@https://code.jquery.com/jquery-2.1.4.min.js:2:29721

Not sure what's causing it since it only seems to happening with Firefox update 40.0

**Comment by ufx** [comment]
I've just tested with that Firefox version and I'm not seeing an issue.  The error indicates that one of the essential libraries the site uses isn't loading.  Do you see a bunch of code if you visit this link http://www.garlandtools.org/db/js/doT.min.js?  Does anything happen if you click the hold down the shift key while you click the refresh button on the page that has an error?

**Comment by MesTheGod** [comment]
Yeah that link shows a boat load of code for me. Holding shift when clicking my bookmark apparently makes it load. Not sure whats going on o_o

**Comment by ufx** [comment]
It's supposed to display that code =).  I think an error was cached by your browser and got stuck somehow.  That usually fixes itself, but shift+refresh can force that.  Glad it's working again!
