### ISSUE TITLE
Having error when clicking garlandtools database

### ISSUE THREAD

**Issue by plebe07092** [ufx/GarlandTools#38]
It gives out this error

gt.item.initialize@http://www.garlandtools.org/db/js/gt.item.js:16:3
gt.core.initialize@http://www.garlandtools.org/db/js/gt.core.js:27:4
n.Callbacks/j@https://code.jquery.com/jquery-2.1.4.min.js:2:26920
n.Callbacks/k.fireWith@https://code.jquery.com/jquery-2.1.4.min.js:2:27738
.ready@https://code.jquery.com/jquery-2.1.4.min.js:2:29530
I@https://code.jquery.com/jquery-2.1.4.min.js:2:29721

when i click clear settings still this shows up.

**Comment by ufx** [comment]
This looks like a file failed to load.  Try holding shift and clicking the refresh button.  Sometimes you have to whitelist the site with ublock, or some other security software is blocking something important There are no ads on garlandtools.

**Comment by Agewen** [comment]
Same error here.. tried the shift-refresh but not luck

**Comment by ufx** [comment]
Hiya, sorry to hear that.  Do you have any network errors loading resources for the site?  I've found this error nowadays happens because of temporary network conditions (gone after a couple hours), or because there is some software blocking an important part of the site.
