### ISSUE TITLE
Skywatcher

### ISSUE THREAD

**Issue by E7t7t7** [ufx/GarlandTools#39]
gt.item.initialize@http://www.garlandtools.org/db/js/gt.item.js:16:3
gt.core.initialize@http://www.garlandtools.org/db/js/gt.core.js:28:4
n.Callbacks/j@https://code.jquery.com/jquery-2.1.4.min.js:2:26920
n.Callbacks/k.fireWith@https://code.jquery.com/jquery-2.1.4.min.js:2:27738
.ready@https://code.jquery.com/jquery-2.1.4.min.js:2:29530
I@https://code.jquery.com/jquery-2.1.4.min.js:2:29721

**Comment by E7t7t7** [comment]
was working fine then firefox wanted to update and bam broken :(

**Comment by ufx** [comment]
Definitely couldn't load a very important file.  I just updated Firefox and loaded up without trouble.  Maybe it was blocked by an ad blocker or something?  It should print if a file was blocked in either the console or the network tab.
