### ISSUE TITLE
Hunting Tracker

### ISSUE THREAD

**Issue by Ley21** [ufx/GarlandTools#4]
An hunting tracker would be nice. Were people can submit if an hunt mob was killed on there server.

**Comment by ufx** [comment]
My personal opinion on hunt trackers is their usefulness decreases if there are more of them.  If someone marks deaths on Ariyala's tracker but not ffxivhunt.com and vice versa, the information on both is less accurate.  So while I'd like to add something like this, I'll only consider it if the other trackers open an API for exchange.

**Comment by IrealiTY** [comment]
IIRC Both of the rely on data provided by [Guildwork](http://guildwork.com/games/ffxiv#/phoenix/hunts) and also sync it to GW if data is entered through both sites - not sure about that though
