### ISSUE TITLE
db error

### ISSUE THREAD

**Issue by Saberawr** [ufx/GarlandTools#42]
gt.time.formatTime@http://www.garlandtools.org/db/js/gt.time.js:108:10
gt.time.initialize@http://www.garlandtools.org/db/js/gt.time.js:18:16
gt.core.initialize@http://www.garlandtools.org/db/js/gt.core.js:31:4
n.Callbacks/j@https://code.jquery.com/jquery-2.1.4.min.js:2:26920
n.Callbacks/k.fireWith@https://code.jquery.com/jquery-2.1.4.min.js:2:27738
.ready@https://code.jquery.com/jquery-2.1.4.min.js:2:29530
I@https://code.jquery.com/jquery-2.1.4.min.js:2:29721
EventListener.handleEvent*n.ready.promise@https://code.jquery.com/jquery-2.1.4.min.js:2:29832
@https://code.jquery.com/jquery-2.1.4.min.js:2:29924
@https://code.jquery.com/jquery-2.1.4.min.js:2:207
@https://code.jquery.com/jquery-2.1.4.min.js:2:2

**Comment by ufx** [comment]
Could I ask what browser you're using?

**Comment by Saberawr** [comment]
Firefox Nightly
50.0a1 (2016-07-12)

**Comment by Saberawr** [comment]
I should add that refreshing + a cache-ignored refresh both did not solve anything.

**Comment by ufx** [comment]
I just installed the Firefox nightly to reproduce, but everything is working on my end.

Do you see any error message above the stack trace you posted, like "undefined has no properties" or "can't convert null to object"?

**Comment by Saberawr** [comment]
db: https://r.kyaa.sg/qbslgk.png
bell: https://r.kyaa.sg/qbrahs.png

**Comment by Saberawr** [comment]
Nothing has changed on my end, yet after taking these screenshots and clicking a link to garland from xivdb (specifically this link: http://www.garlandtools.org/db/#item/15655 ) everything started working again normally, though my bell & db settings & lists are gone from both spots.

**Comment by ufx** [comment]
Huh, that's strange how there was no exception message on that stack screenshot.  I just did a deployment too.  Sorry you lost your lists, but glad it's working again.

**Comment by Saberawr** [comment]
I have no idea why but it's still a problem now. Any other information I could provide which would be helpful?

**Comment by ufx** [comment]
Yes, if you don't mind.  With the database site open, could you open a Javascript console and enter the following:

(new Date()).toLocaleTimeString(navigator.language, gt.time.hoursMinutesSeconds)

Let me know what it prints?  If you're unfamiliar with how to open the console, this page (https://en.wikipedia.org/wiki/Wikipedia:Reporting_JavaScript_errors) can give you instructions.  Thanks!

**Comment by Saberawr** [comment]
https://r.kyaa.sg/rfjwvo.png
`RangeError: invalid language tag: `

**Comment by ufx** [comment]
Aha, we're getting closer!  What does this print?

navigator.language

**Comment by Saberawr** [comment]
`
navigator.language
""
`

**Comment by ufx** [comment]
That's really strange, but I know exactly what's wrong now.  I'll have a fix deployed in a minute - will update here when it's done.

**Comment by ufx** [comment]
OK, should be fixed when you next refresh the page for both /db and /bell.

**Comment by Saberawr** [comment]
Looks to be working so far

**Comment by ufx** [comment]
Awesome!  I think you're either using some kind of privacy extension that blocks the language of your browser, or maybe some odd language settings on your computer.  Either way, I have it detecting that and falling back to English.  Thanks for helping me debug this.
